//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCrud_JorgeCorrea.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class testjcEntities : DbContext
    {
        public testjcEntities()
            : base("name=testjcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<employee> employee { get; set; }
    
        public virtual ObjectResult<TotalEmployeesByDepartment> GetTotalEmployeesByDepartment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TotalEmployeesByDepartment>("GetTotalEmployeesByDepartment");
        }
    }
}
